In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
raw_data_dir = "/content/drive/MyDrive/CS 224N Project/Evaluation/Data/Raw data/"

In [ ]:
file_names = ['abortion.csv', 'before_iraq.csv', 'firearms.csv', 'main_iraq.csv']

In [ ]:
def get_data(file_name, data_dir=raw_data_dir):
  data = pd.read_csv(data_dir + file_name, index_col=None)
  np.shape(data)
  return data

In [ ]:
def get_train_test_split(X, y):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
  return (X_train, X_test, y_train, y_test)

# Processing data

In [ ]:
datasets = {"abortion": None, "before_iraq": None, "firearms": None, "main_iraq": None}
labels = {"abortion": None, "before_iraq": None, "firearms": None, "main_iraq": None}

## Abortion dataset

In [ ]:
abortion_df = get_data('abortion.csv')
print(abortion_df.columns)
print(abortion_df.shape)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'speech', 'date', 'word_count', 'state',
       'party'],
      dtype='object')
(9332, 7)

In [ ]:
abortion_data = abortion_df[['speech', 'date', 'word_count', 'state']].copy()
print(abortion_data.shape)

(9332, 4)

In [ ]:
abortion_labels = abortion_df[['party']].copy()
print(abortion_labels.shape)

(9332, 1)

In [ ]:
datasets["abortion"] = abortion_data
labels["abortion"] = abortion_labels

## Before Iraq dataset

In [ ]:
before_iraq_df = get_data('before_iraq_finalized.csv')
print(before_iraq_df.columns)
print(before_iraq_df.shape)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'speech', 'date', 'word_count', 'state',
       'party'],
      dtype='object')
(9748, 7)

In [ ]:
before_iraq_data = before_iraq_df[['speech', 'date', 'word_count', 'state']].copy()
print(before_iraq_data.shape)

(9748, 4)

In [ ]:
before_iraq_labels = before_iraq_df[['party']].copy()
print(before_iraq_labels.shape)

(9748, 1)

In [ ]:
datasets["before_iraq"] = before_iraq_data
labels["before_iraq"] = before_iraq_labels

## Firearms dataset

In [ ]:
firearms_df = get_data('firearms.csv')
print(firearms_df.columns)
print(firearms_df.shape)

Index(['Unnamed: 0.1', 'Unnamed: 0', 'speech', 'date', 'word_count', 'state',
       'party'],
      dtype='object')
(2652, 7)

In [ ]:
firearms_data = firearms_df[['speech', 'date', 'word_count', 'state']].copy()
print(firearms_data.shape)

(2652, 4)

In [ ]:
firearms_labels = firearms_df[['party']].copy()
print(firearms_labels.shape)

(2652, 1)

In [ ]:
datasets["firearms"] = firearms_data
labels["firearms"] = firearms_labels

## Main Iraq dataset

In [ ]:
main_iraq_df = get_data('main_iraq.csv')
print(main_iraq_df.columns)
print(main_iraq_df.shape)

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'speech', 'date',
       'word_count', 'state', 'party', 'iraq_count'],
      dtype='object')
(10406, 9)

In [ ]:
main_iraq_data = main_iraq_df[['speech', 'date', 'word_count', 'state', 'iraq_count']].copy()
print(main_iraq_data.shape)

(10406, 5)

In [ ]:
main_iraq_labels = main_iraq_df[['party']].copy()
print(main_iraq_labels.shape)

(10406, 1)

In [ ]:
datasets["main_iraq"] = main_iraq_data
labels["main_iraq"] = main_iraq_labels

## Review datasets and labels

In [ ]:
datasets['main_iraq'].head(5)

,speech,date,word_count,state,iraq_count
0,Mr. Speaker. I rise to express my concern for ...,2003-05-01,797,CA,7
1,Mr. President. I rise this morning to offer a ...,2003-05-01,909,TX,7
2,Mr. President. we rise today to discuss the ca...,2003-05-01,1452,OR,14
3,Mr. President. that is an eloquent summation a...,2003-05-01,331,NY,4
4,Mr. President. I rise to share with the Member...,2003-05-05,386,NV,2

In [ ]:
labels['main_iraq'].head(5)

  party
0     D
1     R
2     D
3     D
4     R

# Train test split

In [ ]:
train_data_dir = "/content/drive/MyDrive/CS 224N Project/Evaluation/Data/Processed data/Train/"
test_data_dir = "/content/drive/MyDrive/CS 224N Project/Evaluation/Data/Processed data/Test/"

In [ ]:
## Should only ever load files once, commenting out to prevent rerunning this cell
# for topic in datasets.keys():
#   dataset = datasets[topic]
#   corr_labels = labels[topic]
#   x_train, x_test, y_train, y_test = get_train_test_split(dataset, corr_labels)

#   x_train.to_csv(train_data_dir + topic + "_data.csv", index=False)
#   x_test.to_csv(test_data_dir + topic + "_data.csv", index=False)
#   y_train.to_csv(train_data_dir + topic + "_labels.csv", index=False)
#   y_test.to_csv(test_data_dir + topic + "_labels.csv", index=False)